dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
install:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - sudo apt-get remove cmake
  - sudo apt-get purge cmake
  - wget https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.sh
  - sudo sh cmake-3.8.2-Linux-x86_64.sh --prefix=/opt/cmake
  - sudo ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
  - rm -f cmake-3.8.2-Linux-x86_64.sh
  - git clone https://github.com/actor-framework/actor-framework.git
  - pushd actor-framework && ./configure && make && sudo make install && popd
  - rm -Rf actor-framework
script:
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - gcc -v && g++ -v && cd ./build && cmake .. && make