sudo: required
cache:
  directories:
    - $HOME/.cache/
language:
  - cpp
matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      env:
        - CACHE_KEY=trusty-gcc-5
        - CC=/usr/bin/gcc-5
        - CXX=/usr/bin/g++-5
      compiler:
        - gcc-5
        - g++-5
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
      env:
        - CACHE_KEY=trusty-gcc-6
        - CC=/usr/bin/gcc-6
        - CXX=/usr/bin/g++-6
      compiler:
        - gcc-6
        - g++-6
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - CACHE_KEY=trusty-clang-4.0
        - CC=clang-4.0
        - CXX=clang++-4.0
      compiler:
        - clang-4.0
        - lang++-4.0
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty
          packages:
            - clang-5.0
      env:
        - CACHE_KEY=trusty-clang-5.0
        - CC=clang-5.0
        - CXX=clang++-5.0
      compiler:
        - clang-5.0
        - lang++-5.0
    - os: osx
      osx_image: xcode8
      env:
        - CACHE_KEY=xcode8-gcc-5
        - CC=gcc-5
        - CXX=g++-5
      compiler:
        - gcc-5
        - g++-5
      before_install:
        - brew install gcc5
    - os: osx
      osx_image: xcode8
      env:
        - CACHE_KEY=xcode8-gcc-6
        - CC=gcc-6
        - CXX=g++-6
      compiler:
        - gcc-6
        - g++-6
      before_install:
        - brew install gcc
install:
  - echo "CC=${CC}"
  - echo "CXX=${CXX}"
  - echo "CACHE_KEY=${CACHE_KEY}"
  - mkdir -p $HOME/.cache/$CACHE_KEY
  - sudo sh $TRAVIS_BUILD_DIR/.ci-scripts/install-cmake.sh
  - sudo sh $TRAVIS_BUILD_DIR/.ci-scripts/install-caf.sh
script:
  - cd ./build && cmake .. && make
